version: 1.0.{build}

image: Visual Studio 2019
 
install:  
- cmd: curl -O https://download.visualstudio.microsoft.com/download/pr/046165a4-10d4-4156-8e65-1d7b2cbd304e/a4c7b01f6bf7199669a45ab6a03803ac/dotnet-sdk-3.1.412-win-x64.exe
- cmd: dotnet-sdk-3.1.412-win-x64.exe /install /quiet /norestart /log install.log   

branches:
  only:
  - dev
  
build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: artifacts/packages/*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/damiani/
  api_key:
    secure: XOm6HAYrck/gljqdDrLWHopqnOs/FwbstHoi61nIEX6SJNUyccAaLJ4hjsyHoSF8
  skip_symbols: true
  on:
    branch: dev
    
#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/
  files:
    - ./*.md
